// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgsFFsfB8AzGL2c2nnB9XHyJO3080Mwg',
    appId: '1:349222374497:web:d307a85b1365ba63836e20',
    messagingSenderId: '349222374497',
    projectId: 'tic-tac-toe-e7090',
    authDomain: 'tic-tac-toe-e7090.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-e7090-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-e7090.appspot.com',
    measurementId: 'G-GBW9L0ZCBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5gk2nqra4w5h0yKZa0glIkWvBu5msFw',
    appId: '1:349222374497:android:834edc38f90d32f5836e20',
    messagingSenderId: '349222374497',
    projectId: 'tic-tac-toe-e7090',
    databaseURL: 'https://tic-tac-toe-e7090-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-e7090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4akyoePlIDS6Ad2kRnfr__J3Gbe0dGs',
    appId: '1:349222374497:ios:26173acc8749e4fb836e20',
    messagingSenderId: '349222374497',
    projectId: 'tic-tac-toe-e7090',
    databaseURL: 'https://tic-tac-toe-e7090-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-e7090.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4akyoePlIDS6Ad2kRnfr__J3Gbe0dGs',
    appId: '1:349222374497:ios:71a33453e5f62f1c836e20',
    messagingSenderId: '349222374497',
    projectId: 'tic-tac-toe-e7090',
    databaseURL: 'https://tic-tac-toe-e7090-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-e7090.appspot.com',
    iosBundleId: 'com.example.ticTacToe.RunnerTests',
  );
}
